# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TaleTree' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaleTree

 pod 'IQKeyboardManagerSwift'
 pod 'Alamofire', '~> 4.4'
 pod 'SVProgressHUD'
 pod 'SDWebImage'
 pod 'TZImagePickerControllerSwift'
 pod 'Firebase/Analytics'
 pod 'Firebase/Crashlytics'
 pod 'BottomPopup'
 pod 'MJRefresh'
 pod 'WMSegmentControl'

  target 'TaleTreeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaleTreeUITests' do
    # Pods for testing
  end

end
